version: '3'

services:

    # Proxies requests to internal services
    website:
        image: kalmusb/website-nginx:latest
        container_name: website
        volumes:
            - /etc/letsencrypt/:/etc/nginx/ssl 
            - /var/log/nginx:/var/log/nginx 
            - /app/portfolio/static:/app/static 
            - /app/portfolio/blog:/app/blog 
            - /app/portfolio/blog/categories:/app/categories
            - /app/portfolio/blog/css:/app/css
            - /app/portfolio/blog/fontawesome:/app/fontawesome
            - /app/portfolio/blog/fonts:/app/fonts
            - /app/portfolio/blog/img:/app/img
            - /app/portfolio/blog/js:/app/js
            - /app/portfolio/blog/page:/app/page
            - /app/portfolio/blog/post:/app/post
            - /app/portfolio/blog/posts:/app/posts
            - /app/portfolio/blog/tags:/app/tags
            - /app/portfolio/blog/video:/app/video
        ports:
            - 80:80
            - 443:443
        restart: always
        networks:
            - flask-proxy

    # handles contact form and sends email to my mailbox
    flask-email:
        image: kalmusb/website-email
        container_name: flask-email

        volumes:
            - /app/email/env:/app/env 
            - /var/log/flask-email/:/app/log/ 
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - website
        networks:
            - flask-proxy
networks:
    flask-proxy:
